f = open('code\ch04\script1.py')
# print(f.__next__(),end='')
# print(f.__next__(),end='')
# print(f.__next__(),end='')
# print(f.__next__(),end='')
# print(f.__next__(),end='')
# print(f.__next__(),end='')
# print(f.__next__(),end='')

# i = next(f)
print(next(f),end='')
print(next(f),end='')
print(next(f),end='')
print(next(f),end='')
print(next(f),end='')
print(next(f),end='')
print(next(f),end='')
